name: Check Pull Request

on:
  pull_request_target:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Notify PR check is paused
        run: echo "check_pull_request is temporarily paused"