name: "[Dispatch] Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "enter version(x.y.z)"
        required: true
        default: "2.0.0"
      container_arch:
        type: choice
        description: "choose container architecture"
        default: linux/amd64,linux/arm64
        options:
          - "linux/amd64"
          - "linux/amd64,linux/arm64"

jobs:
  call-workflow:
    uses: spaceone-dev/actions/.github/workflows/called_python_service_dispatch_release.yml@master
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
      container_arch: ${{ github.event.inputs.container_arch }}
